# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icerikyukle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(812, 595)
        self.baslikLabel = QtWidgets.QLabel(Form)
        self.baslikLabel.setGeometry(QtCore.QRect(40, 0, 121, 99))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.baslikLabel.setFont(font)
        self.baslikLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.baslikLabel.setObjectName("baslikLabel")
        self.oncekiButon = QtWidgets.QPushButton(Form)
        self.oncekiButon.setGeometry(QtCore.QRect(570, 510, 51, 41))
        self.oncekiButon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/sol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oncekiButon.setIcon(icon)
        self.oncekiButon.setIconSize(QtCore.QSize(32, 32))
        self.oncekiButon.setObjectName("oncekiButon")
        self.sonrakiButon = QtWidgets.QPushButton(Form)
        self.sonrakiButon.setGeometry(QtCore.QRect(710, 510, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sonrakiButon.setFont(font)
        self.sonrakiButon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/sağ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sonrakiButon.setIcon(icon1)
        self.sonrakiButon.setIconSize(QtCore.QSize(32, 32))
        self.sonrakiButon.setObjectName("sonrakiButon")
        self.sayfa = QtWidgets.QLabel(Form)
        self.sayfa.setGeometry(QtCore.QRect(44, 513, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sayfa.setFont(font)
        self.sayfa.setObjectName("sayfa")
        self.aciklama = QtWidgets.QTextEdit(Form)
        self.aciklama.setGeometry(QtCore.QRect(40, 80, 731, 411))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.aciklama.setFont(font)
        self.aciklama.setObjectName("aciklama")
        self.baslikLine = QtWidgets.QLineEdit(Form)
        self.baslikLine.setGeometry(QtCore.QRect(201, 38, 571, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.baslikLine.setFont(font)
        self.baslikLine.setObjectName("baslikLine")
        self.kaydetButon = QtWidgets.QPushButton(Form)
        self.kaydetButon.setEnabled(False)
        self.kaydetButon.setGeometry(QtCore.QRect(348, 510, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kaydetButon.setFont(font)
        self.kaydetButon.setObjectName("kaydetButon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kurs"))
        self.baslikLabel.setText(_translate("Form", "Başlık"))
        self.sayfa.setText(_translate("Form", "Sayfa : 5"))
        self.kaydetButon.setText(_translate("Form", "Kaydet"))
