# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kurs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(812, 595)
        self.baslikLabel = QtWidgets.QLabel(Form)
        self.baslikLabel.setGeometry(QtCore.QRect(40, 0, 419, 99))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.baslikLabel.setFont(font)
        self.baslikLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.baslikLabel.setObjectName("baslikLabel")
        self.aciklamaLabel = QtWidgets.QLabel(Form)
        self.aciklamaLabel.setGeometry(QtCore.QRect(40, 90, 741, 401))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.aciklamaLabel.setFont(font)
        self.aciklamaLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aciklamaLabel.setScaledContents(False)
        self.aciklamaLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.aciklamaLabel.setWordWrap(True)
        self.aciklamaLabel.setObjectName("aciklamaLabel")
        self.oncekiButon = QtWidgets.QPushButton(Form)
        self.oncekiButon.setGeometry(QtCore.QRect(530, 510, 51, 41))
        self.oncekiButon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/sol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oncekiButon.setIcon(icon)
        self.oncekiButon.setIconSize(QtCore.QSize(32, 32))
        self.oncekiButon.setObjectName("oncekiButon")
        self.sonrakiButon = QtWidgets.QPushButton(Form)
        self.sonrakiButon.setGeometry(QtCore.QRect(710, 510, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sonrakiButon.setFont(font)
        self.sonrakiButon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/sağ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sonrakiButon.setIcon(icon1)
        self.sonrakiButon.setIconSize(QtCore.QSize(32, 32))
        self.sonrakiButon.setObjectName("sonrakiButon")
        self.sayfa = QtWidgets.QLabel(Form)
        self.sayfa.setGeometry(QtCore.QRect(44, 513, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sayfa.setFont(font)
        self.sayfa.setObjectName("sayfa")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kurs"))
        self.baslikLabel.setText(_translate("Form", "Bilgi Teknolojilerine Giriş"))
        self.aciklamaLabel.setText(_translate("Form", "Yazılım, donanım ve bilişim dünyasına ait temel kavramların öğretilmesi.\n"
"Kursiyerlerin ilerleyen dersler boyunca yazılım yeteneklerini geliştirmesi hedeflenir.\n"
"Oldukça yaygın bir şekilde kullanılan yazılım dilleri konusunda fikir sahibi olması sağlanır."))
        self.sayfa.setText(_translate("Form", "Sayfa : 5"))
