# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kursliste.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 292)
        self.tablo = QtWidgets.QTableWidget(Form)
        self.tablo.setGeometry(QtCore.QRect(0, 60, 451, 231))
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(4)
        self.tablo.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        self.kursBox = QtWidgets.QComboBox(Form)
        self.kursBox.setGeometry(QtCore.QRect(90, 20, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.kursBox.setFont(font)
        self.kursBox.setObjectName("kursBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 39))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kurs Listesi"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ad"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Soyad"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "E-Posta"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Telefon"))
        self.label.setText(_translate("Form", "Kurs :"))
