# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kursolustur.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(284, 473)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 241, 124))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.kursadi = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.kursadi.setFont(font)
        self.kursadi.setObjectName("kursadi")
        self.verticalLayout.addWidget(self.kursadi)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.egitmenBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.egitmenBox.setFont(font)
        self.egitmenBox.setObjectName("egitmenBox")
        self.verticalLayout.addWidget(self.egitmenBox)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.aciklama = QtWidgets.QTextEdit(Form)
        self.aciklama.setGeometry(QtCore.QRect(20, 170, 241, 81))
        self.aciklama.setObjectName("aciklama")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.kazanimlar = QtWidgets.QTextEdit(Form)
        self.kazanimlar.setGeometry(QtCore.QRect(20, 290, 241, 81))
        self.kazanimlar.setObjectName("kazanimlar")
        self.olusturButon = QtWidgets.QPushButton(Form)
        self.olusturButon.setGeometry(QtCore.QRect(70, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.olusturButon.setFont(font)
        self.olusturButon.setObjectName("olusturButon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kurs Oluştur"))
        self.label.setText(_translate("Form", "Kurs Adı"))
        self.label_2.setText(_translate("Form", "Eğitmen"))
        self.label_3.setText(_translate("Form", "Açıklama"))
        self.label_4.setText(_translate("Form", "Kazanımlar"))
        self.olusturButon.setText(_translate("Form", "Oluştur"))
